import type { Decomposition, PatchFile, Patchset } from "@rennet/protocol";
import { describe, expect, it } from "vitest";
import {
  DEFAULT_MAX_CHUNK_LOC,
  DEGRADED_SYMBOL_EXTRACTOR,
  decompose,
  type SymbolExtractor,
} from "./decomposition";

// ── Fixture builders ─────────────────────────────────────────────────────────

interface HunkSpec {
  oldStart?: number;
  newStart?: number;
  /** Unified-diff body lines, each prefixed with `+`, `-`, or ` `. */
  lines: string[];
}

function filePatch(path: string, hunks: HunkSpec[]): string {
  const head = `diff --git a/${path} b/${path}\n--- a/${path}\n+++ b/${path}\n`;
  const body = hunks
    .map((hunk) => {
      const oldCount = hunk.lines.filter((l) => l[0] === "-" || l[0] === " ").length;
      const newCount = hunk.lines.filter((l) => l[0] === "+" || l[0] === " ").length;
      const header = `@@ -${hunk.oldStart ?? 1},${oldCount} +${hunk.newStart ?? 1},${newCount} @@`;
      return `${header}\n${hunk.lines.join("\n")}`;
    })
    .join("\n");
  return `${head}${body}\n`;
}

function file(path: string, patch: string, extra: Partial<PatchFile> = {}): PatchFile {
  return {
    path,
    status: "modified",
    additions: null,
    deletions: null,
    binary: false,
    patch,
    ...extra,
  };
}

let counter = 0;
function patchset(files: PatchFile[]): Patchset {
  counter += 1;
  return {
    id: `ps_${counter}`,
    createdAt: "2026-01-01T00:00:00.000Z",
    repository: {
      id: "repo",
      root: "/repo",
      commonDir: "/repo/.git",
      baseRef: "origin/main",
      baseOid: "0".repeat(40),
      headOid: "1".repeat(40),
    },
    files,
    rawDiff: "",
    byteLength: 0,
    truncated: false,
  };
}

/** Every hunk lands in exactly one chunk; residue is empty (totality, V100). */
function assertTotality(result: Decomposition): void {
  const placed = result.chunks.flatMap((c) => c.hunkIds);
  expect(new Set(placed).size).toBe(placed.length); // no duplication (V101)
  expect([...placed].sort()).toEqual(result.hunks.map((h) => h.id).sort());
  expect(result.residue).toEqual([]);
}

/** readingOrder covers every chunk once and respects every edge (V103). */
function assertTopological(result: Decomposition): void {
  expect([...result.readingOrder].sort()).toEqual(result.chunks.map((c) => c.chunkId).sort());
  const position = new Map(result.readingOrder.map((id, index) => [id, index]));
  for (const edge of result.edges) {
    expect(position.get(edge.from)).toBeLessThan(position.get(edge.to) ?? -1);
  }
}

function classOf(result: Decomposition, filePath: string): string | null {
  const hunk = result.hunks.find((h) => h.filePath === filePath);
  const classification = result.classifications.find((c) => c.hunkId === hunk?.id);
  return classification?.mechanical ?? null;
}

// ── Mechanical classification (golden fixtures) ──────────────────────────────

describe("classification", () => {
  it("marks a lockfile mechanical:lockfile", () => {
    const result = decompose(
      patchset([
        file("pnpm-lock.yaml", filePatch("pnpm-lock.yaml", [{ lines: ["+  foo: 1.0.0"] }])),
      ]),
    );
    expect(classOf(result, "pnpm-lock.yaml")).toBe("lockfile");
  });

  it("marks a vendored path mechanical:vendored", () => {
    const path = "node_modules/left-pad/index.js";
    const result = decompose(
      patchset([file(path, filePatch(path, [{ lines: ["+module.exports = 1;"] }]))]),
    );
    expect(classOf(result, path)).toBe("vendored");
  });

  it("marks a generated path mechanical:generated", () => {
    const path = "dist/bundle.min.js";
    const result = decompose(patchset([file(path, filePatch(path, [{ lines: ["+var a=1;"] }]))]));
    expect(classOf(result, path)).toBe("generated");
  });

  it("marks a @generated marker mechanical:generated even off a source path", () => {
    const path = "src/api.ts";
    const result = decompose(
      patchset([
        file(
          path,
          filePatch(path, [
            { lines: ["+// @generated by openapi-codegen", "+export const x = 1;"] },
          ]),
        ),
      ]),
    );
    expect(classOf(result, path)).toBe("generated");
  });

  it("does NOT mark a substantive hand-edit generated when the marker is only in the file BODY", () => {
    // A real hand-edit deep in the file. The body carries a stray
    // "// do not edit by hand" comment (e.g. above a codegen'd block), far from
    // the header region. File-scoped marker detection would stamp EVERY hunk in
    // this file `generated` and hide the edit in the skimmed appendix — the
    // worst false-negative direction (acceptance #5). Header-scoping must not.
    const path = "src/api.ts";
    const result = decompose(
      patchset([
        file(
          path,
          filePatch(path, [
            {
              newStart: 40,
              lines: [
                " // do not edit by hand",
                "-const rate = computeRate(1);",
                "+const rate = computeRate(2);",
              ],
            },
          ]),
        ),
      ]),
    );
    expect(classOf(result, path)).toBeNull();
    // and the change reaches a substantive chunk, not the skimmed appendix.
    const substantive = result.chunks.filter((c) => c.kind === "substantive");
    expect(substantive.map((c) => c.title)).toContain(path);
    assertTotality(result);
  });

  it("still marks generated when the marker sits in the file HEADER region (no over-correction)", () => {
    // Control: a genuine generated file whose banner sits at the very top must
    // still classify `generated`. The fix narrows WHERE the marker is honoured,
    // it does not remove generated-detection.
    const path = "src/client.ts";
    const result = decompose(
      patchset([
        file(
          path,
          filePatch(path, [
            {
              newStart: 1,
              lines: [
                "+// Code generated by protoc-gen. DO NOT EDIT.",
                "+export const version = 3;",
              ],
            },
          ]),
        ),
      ]),
    );
    expect(classOf(result, path)).toBe("generated");
  });

  it("honours a marker exactly on the last header line (new line 10, boundary inclusive)", () => {
    // Cursor coverage: the marker is not at newStart. A hunk starting at line 5
    // walks context lines up to new-file line 10, where the banner sits. Line 10
    // is inside the header region, so it must still classify `generated`. Guards
    // against an off-by-one that would exclude the boundary line.
    const path = "src/boundary.ts";
    const result = decompose(
      patchset([
        file(
          path,
          filePatch(path, [
            {
              newStart: 5,
              lines: [
                " a", // new 5
                " b", // new 6
                " c", // new 7
                " d", // new 8
                " e", // new 9
                "+// Code generated by gen. DO NOT EDIT.", // new 10 (last header line)
              ],
            },
          ]),
        ),
      ]),
    );
    expect(classOf(result, path)).toBe("generated");
  });

  it("does NOT honour a marker one line past the header (new line 11) even when the hunk starts early", () => {
    // Cursor coverage that DISTINGUISHES the real implementation from a naive
    // `newStart <= 10 && searchEntireHunk()`. The hunk starts at line 5, so the
    // early-exit guard does not fire, but the marker lands on new-file line 11 —
    // one past the header — alongside a real code edit. A whole-hunk search would
    // wrongly stamp this `generated`; the header-scoped cursor must not.
    const path = "src/past.ts";
    const result = decompose(
      patchset([
        file(
          path,
          filePatch(path, [
            {
              newStart: 5,
              lines: [
                " a", // new 5
                " b", // new 6
                " c", // new 7
                " d", // new 8
                " e", // new 9
                " f", // new 10
                "+// do not edit by hand", // new 11 (past header)
                "-const rate = computeRate(1);",
                "+const rate = computeRate(2);", // new 12
              ],
            },
          ]),
        ),
      ]),
    );
    expect(classOf(result, path)).toBeNull();
  });

  it("skips deleted lines when counting new-file position (top-of-file regen behind deletions)", () => {
    // Cursor coverage that DISTINGUISHES the real implementation from one that
    // wrongly advances the new-file counter on deleted lines. Ten deleted lines
    // precede a banner that is added at new-file line 1. Deleted lines do not
    // exist in the new file, so the banner is at line 1 (inside the header) and
    // must classify `generated`. A cursor that counted the deletions would place
    // the banner at line 11 and miss it.
    const path = "src/regen.ts";
    const result = decompose(
      patchset([
        file(
          path,
          filePatch(path, [
            {
              newStart: 1,
              lines: [
                "-old line 1",
                "-old line 2",
                "-old line 3",
                "-old line 4",
                "-old line 5",
                "-old line 6",
                "-old line 7",
                "-old line 8",
                "-old line 9",
                "-old line 10",
                "+// Code generated by gen. DO NOT EDIT.", // new 1
                "+export const version = 2;", // new 2
              ],
            },
          ]),
        ),
      ]),
    );
    expect(classOf(result, path)).toBe("generated");
  });

  it("marks a whitespace-only reindent mechanical:formatting-only", () => {
    const path = "src/format.ts";
    const result = decompose(
      patchset([file(path, filePatch(path, [{ lines: ["-  doThing();", "+    doThing();"] }]))]),
    );
    expect(classOf(result, path)).toBe("formatting-only");
  });

  it("marks a pure rename mechanical:pure-rename", () => {
    const patch = "diff --git a/old.ts b/new.ts\nrename from old.ts\nrename to new.ts\n";
    const result = decompose(
      patchset([
        file("new.ts", patch, {
          status: "renamed",
          previousPath: "old.ts",
          additions: 0,
          deletions: 0,
        }),
      ]),
    );
    expect(classOf(result, "new.ts")).toBe("pure-rename");
  });

  it("marks a mode-only change mechanical:mode-only", () => {
    const patch = "diff --git a/run.sh b/run.sh\nold mode 100644\nnew mode 100755\n";
    const result = decompose(patchset([file("run.sh", patch, { additions: 0, deletions: 0 })]));
    expect(classOf(result, "run.sh")).toBe("mode-only");
  });

  it("leaves a real code change substantive (mechanical null)", () => {
    const path = "src/logic.ts";
    const result = decompose(
      patchset([file(path, filePatch(path, [{ lines: ["-const a = 1;", "+const a = 2;"] }]))]),
    );
    expect(classOf(result, path)).toBeNull();
    const hunk = result.hunks.find((h) => h.filePath === path);
    const classification = result.classifications.find((c) => c.hunkId === hunk?.id);
    expect(classification?.kind).toBe("substantive");
  });

  it("routes mechanical hunks to appendix chunks, substantive to substantive chunks", () => {
    const result = decompose(
      patchset([
        file("pnpm-lock.yaml", filePatch("pnpm-lock.yaml", [{ lines: ["+  a: 1"] }])),
        file("src/logic.ts", filePatch("src/logic.ts", [{ lines: ["+const a = 1;"] }])),
      ]),
    );
    const appendix = result.chunks.filter((c) => c.kind === "appendix");
    const substantive = result.chunks.filter((c) => c.kind === "substantive");
    expect(appendix.map((c) => c.title)).toEqual(["pnpm-lock.yaml"]);
    expect(substantive.map((c) => c.title)).toEqual(["src/logic.ts"]);
    assertTotality(result);
  });
});

// ── Blocking states (R18): the false-clear floor ────────────────────────────
//
// R18: binary / submodule / truncated inputs are first-class and incomplete
// ingestion is BLOCKING (in `blockingStates`): an absence of findings over
// un-ingested content must never let a done or publish gate read "reviewed
// clean". Each required test directly exercises one false-clear or false-positive
// direction and is red-proofed independently.

/** The DIFF_TRUNCATION_MARKER the capture appends when it truncates a file diff. */
const TRUNC = "[diff truncated by Rennet]";

describe("blocking states (R18)", () => {
  it("required blocking contract: truncated patchset", () => {
    // The literal original bug: `decompose` never read `patchset.truncated`, so a
    // capture that hit its byte cap produced a decomposition indistinguishable
    // from a complete one, leaving a done or publish gate nothing to block on.
    const result = decompose({
      ...patchset([
        file("src/logic.ts", filePatch("src/logic.ts", [{ lines: ["+const a = 1;"] }])),
      ]),
      truncated: true,
    });
    // The visible prefix still decomposes and reads complete on its own …
    assertTotality(result);
    expect(result.chunks.filter((c) => c.kind === "substantive").length).toBe(1);
    // The visible prefix stays reviewable, but the missing tail blocks completion.
    expect(result.blockingStates).toContainEqual(
      expect.objectContaining({ reason: "truncated", path: null }),
    );
  });

  it("blocks a per-file DIFF_TRUNCATION_MARKER using the producer's terminal frame", () => {
    const path = "src/big.ts";
    // `visible()` emits the marker as a terminal `…\n\n<marker>` frame.
    const patch = `${filePatch(path, [{ lines: ["+const a = 1;"] }]).trimEnd()}\n\n${TRUNC}`;
    const result = decompose(patchset([file(path, patch)]));
    expect(result.blockingStates).toContainEqual(
      expect.objectContaining({ reason: "truncated", path }),
    );
  });

  it("required blocking contract: binary file stays out of substantive review", () => {
    // Original bug: a bare binary with no path signal fell through to
    // `substantive`, so a changed blob read as reviewed content.
    const path = "assets/logo.png";
    const result = decompose(patchset([file(path, "", { binary: true })]));
    expect(classOf(result, path)).toBe("binary");
    // It lands in the skimmable appendix, not a substantive chunk.
    expect(result.chunks.filter((c) => c.kind === "substantive")).toEqual([]);
    expect(result.chunks.filter((c) => c.kind === "appendix").map((c) => c.title)).toEqual([path]);
    expect(result.blockingStates).toContainEqual(
      expect.objectContaining({ reason: "binary", path }),
    );
    assertTotality(result);
    assertTopological(result);
  });

  it("required blocking contract: submodule change", () => {
    // Original bug: a gitlink `Subproject commit` change had no mechanical signal
    // and became a synthetic substantive hunk reading as reviewed content.
    const path = "deps/lib";
    const patch =
      `diff --git a/${path} b/${path}\nindex abc1234..def5678 160000\n--- a/${path}\n+++ b/${path}\n` +
      "@@ -1 +1 @@\n-Subproject commit abc1234000000000000000000000000000000000\n" +
      "+Subproject commit def5678000000000000000000000000000000000\n";
    const result = decompose(patchset([file(path, patch)]));
    expect(classOf(result, path)).toBe("submodule");
    expect(result.chunks.filter((c) => c.kind === "substantive")).toEqual([]);
    expect(result.blockingStates).toContainEqual(
      expect.objectContaining({ reason: "submodule", path }),
    );
    assertTotality(result);
  });

  it("required blocking contract: normal patchset stays unblocked", () => {
    // The green direction a blocker like this usually breaks: an ordinary text
    // change is fully ingested, so `blockingStates` must be empty.
    const result = decompose(
      patchset([
        file(
          "src/logic.ts",
          filePatch("src/logic.ts", [{ lines: ["-const a = 1;", "+const a = 2;"] }]),
        ),
        file("pnpm-lock.yaml", filePatch("pnpm-lock.yaml", [{ lines: ["+  a: 1"] }])),
      ]),
    );
    expect(result.blockingStates).toEqual([]);
  });

  it("orders blocking states deterministically: patchset-wide first, then per-file by path", () => {
    const bin = "z-assets/a.bin";
    const sub = "a-vendor/lib";
    const subPatch =
      `diff --git a/${sub} b/${sub}\nindex aaa0000..bbb0000 160000\n@@ -1 +1 @@\n` +
      "-Subproject commit aaa0000000000000000000000000000000000000\n" +
      "+Subproject commit bbb0000000000000000000000000000000000000\n";
    const result = decompose({
      ...patchset([file(bin, "", { binary: true }), file(sub, subPatch)]),
      truncated: true,
    });
    // Patchset-wide truncation first; then files in path order (a-vendor < z-assets).
    expect(result.blockingStates.map((state) => [state.reason, state.path])).toEqual([
      ["truncated", null],
      ["submodule", sub],
      ["binary", bin],
    ]);
  });

  // ── Structural detection, not substring (negative controls) ────────────────

  it("does NOT flag a real text file whose ADDED LINE is exactly a pointer-shaped string", () => {
    // The dangerous over-fire (Codex's real-git probe): note.txt's content becomes
    // literally `Subproject commit deadbeef`, so the diff carries a `+Subproject
    // commit <hex>` line with an ordinary `100644` mode. Keying on the pointer body
    // line would hide this real hand-edit in the appendix; keying on the `160000`
    // metadata does not.
    const path = "note.txt";
    const patch =
      `diff --git a/${path} b/${path}\nindex 1111111..2222222 100644\n--- a/${path}\n+++ b/${path}\n` +
      "@@ -1 +1 @@\n-old\n+Subproject commit deadbeef00000000000000000000000000000000\n";
    const result = decompose(patchset([file(path, patch)]));
    expect(classOf(result, path)).toBeNull();
    expect(result.chunks.filter((c) => c.kind === "substantive").map((c) => c.title)).toContain(
      path,
    );
    expect(result.blockingStates).toEqual([]);
  });

  it("detects a submodule via the `index …160000` header alone (no Subproject line)", () => {
    const path = "vendor/lib";
    const patch = `diff --git a/${path} b/${path}\nindex 8cc0857..d9a9186 160000\n`;
    const result = decompose(patchset([file(path, patch)]));
    expect(classOf(result, path)).toBe("submodule");
    expect(result.blockingStates).toContainEqual(
      expect.objectContaining({ reason: "submodule", path }),
    );
  });

  it("detects git's `diff.submodule=log` forms: spaced path, `...`, dirty, and sha-256 OIDs", () => {
    // All are real git outputs (Codex probes). The path may contain spaces, the
    // range may be `..`/`...` ending in `:` or ` (status)`, a dirty working tree
    // shows `contains modified content`, and OIDs may be sha-256 (64 chars).
    const sha256 = `${"a".repeat(64)}..${"b".repeat(64)}`;
    for (const [path, patch] of [
      ["sub module", "Submodule sub module bd72186..0d4dfdc:\n  > two\n"],
      ["vendor/lib", "Submodule vendor/lib a426a56...26627d8 (commits not present)\n"],
      ["sub module", "Submodule sub module contains modified content\n"],
      ["vendor/lib", `Submodule vendor/lib ${sha256}:\n`],
    ] as const) {
      const result = decompose(patchset([file(path, patch)]));
      expect(classOf(result, path)).toBe("submodule");
      expect(result.blockingStates).toContainEqual(
        expect.objectContaining({ reason: "submodule", path }),
      );
    }
  });

  it("does NOT flag an ordinary text file whose line is `Subproject commit <hex>-dirty`", () => {
    // The over-fire the `-dirty` body-line matcher caused: a real 100644 text file
    // adding a pointer-shaped line with git's `-dirty` suffix must stay substantive
    // (VISIBLE), never be stamped submodule and hidden in the appendix. Detection
    // keys only on column-0 metadata, never a forgeable +/- body line.
    const path = "note.txt";
    const oid = "deadbeef00000000000000000000000000000000";
    const patch =
      `diff --git a/${path} b/${path}\nindex 1111111..2222222 100644\n--- a/${path}\n+++ b/${path}\n` +
      `@@ -1 +1 @@\n-old\n+Subproject commit ${oid}-dirty\n`;
    const result = decompose(patchset([file(path, patch)]));
    expect(classOf(result, path)).toBeNull();
    expect(result.chunks.filter((c) => c.kind === "substantive").map((c) => c.title)).toContain(
      path,
    );
    expect(result.blockingStates).toEqual([]);
  });

  it("detects a `GIT binary patch` blob even when the capture left binary:false", () => {
    // The false-clear Codex found: a canonical GIT binary patch with binary:false
    // became a synthetic zero-LOC substantive chunk with no gap.
    const path = "assets/icon.png";
    const patch =
      `diff --git a/${path} b/${path}\n` +
      "index 0000000..1111111 100644\nGIT binary patch\nliteral 8\nzcmZQ$0000\n\n";
    const result = decompose(patchset([file(path, patch, { binary: false })]));
    expect(classOf(result, path)).toBe("binary");
    expect(result.chunks.filter((c) => c.kind === "substantive")).toEqual([]);
    expect(result.blockingStates).toContainEqual(
      expect.objectContaining({ reason: "binary", path }),
    );
  });

  it("does NOT hide the regular half of a gitlink↔file TYPE CHANGE (both directions)", () => {
    // A path that changes between a submodule (160000) and a regular file (100644)
    // emits both a 160000 section and a regular-file section in one PatchFile. The
    // regular text must stay substantive/VISIBLE, not be stamped submodule and
    // hidden in the appendix (the dangerous direction Codex reproduced).
    const path = "src/embedded";
    const gitlinkToFile =
      `diff --git a/${path} b/${path}\ndeleted file mode 160000\nindex abc1234..0000000\n` +
      `--- a/${path}\n+++ /dev/null\n@@ -1 +0,0 @@\n-Subproject commit abc1234000000000000000000000000000000000\n` +
      `diff --git a/${path} b/${path}\nnew file mode 100644\nindex 0000000..036ad28\n` +
      `--- /dev/null\n+++ b/${path}\n@@ -0,0 +1 @@\n+real ordinary text\n`;
    const fileToGitlink =
      `diff --git a/${path} b/${path}\ndeleted file mode 100644\nindex 036ad28..0000000\n` +
      `--- a/${path}\n+++ /dev/null\n@@ -1 +0,0 @@\n-real ordinary text\n` +
      `diff --git a/${path} b/${path}\nnew file mode 160000\nindex 0000000..abc1234\n` +
      `--- /dev/null\n+++ b/${path}\n@@ -0,0 +1 @@\n+Subproject commit abc1234000000000000000000000000000000000\n`;
    for (const patch of [gitlinkToFile, fileToGitlink]) {
      const result = decompose(patchset([file(path, patch)]));
      expect(classOf(result, path)).toBeNull();
      expect(result.chunks.filter((c) => c.kind === "substantive").map((c) => c.title)).toContain(
        path,
      );
      expect(result.blockingStates).toEqual([]);
    }
  });

  it("does NOT flag truncation when the marker text appears mid-body (only the terminal frame counts)", () => {
    const path = "src/x.ts";
    const patch = filePatch(path, [
      { lines: ['+const note = "[diff truncated by Rennet]";', "+const a = 1;"] },
    ]);
    const result = decompose(patchset([file(path, patch)]));
    expect(result.blockingStates).toEqual([]);
  });
});

// ── Hunk-body content is never metadata (#310, core sibling pin) ─────────────

describe("parseFilePatch keeps `+++`/`---`-rendered body lines as hunk body (#310)", () => {
  // #310 named this core parser as a possible sibling of the adapters re-key bug.
  // Audit finding: it is NOT — metadata is read only in the preamble (`current ===
  // null`), hunk headers match the anchored HUNK_HEADER regex, and in-hunk lines are
  // classified by `charAt(0)` alone. This test PINS that: if a refactor ever flattened
  // core into the flat adapters shape (matching `+++ ` anywhere), the added line would
  // be dropped from the body and this reddens.
  it("an added line rendered `+++ b/other.txt` inside a hunk is carried as an addition", () => {
    const path = "changed.txt";
    const patch = filePatch(path, [{ lines: [" context", "+++ b/other.txt", "+ordinary add"] }]);
    const result = decompose(patchset([file(path, patch)]));
    // No metadata effect: every hunk keys to the real file, none to `other.txt`.
    expect(result.hunks.map((h) => h.filePath)).toEqual([path]);
    // The adversarial line is body content: an addition carrying `++ b/other.txt`
    // (its one-character `+` prefix stripped), alongside the ordinary add.
    expect(result.hunks[0]?.addedLines).toEqual(["++ b/other.txt", "ordinary add"]);
  });
});

// ── Chunking and the ≤400 budget ─────────────────────────────────────────────

describe("chunking", () => {
  it("keeps every substantive chunk within the ≤400 budget", () => {
    // Three 200-LOC hunks in one file: greedy-merge → 200+200=400, then 200.
    const hunk = (start: number): HunkSpec => ({
      newStart: start,
      lines: Array.from({ length: 200 }, (_, i) => `+line ${start}_${i}`),
    });
    const path = "src/big.ts";
    const result = decompose(
      patchset([file(path, filePatch(path, [hunk(1), hunk(201), hunk(401)]))]),
    );
    const substantive = result.chunks.filter((c) => c.kind === "substantive");
    for (const chunk of substantive)
      expect(chunk.changedLoc).toBeLessThanOrEqual(DEFAULT_MAX_CHUNK_LOC);
    expect(substantive.map((c) => c.changedLoc)).toEqual([400, 200]);
    assertTotality(result);
  });

  it("splits a 1000-line hunk into ≤400-LOC fragments and chunks", () => {
    const path = "src/huge.ts";
    const lines = Array.from({ length: 1000 }, (_, i) => `+row ${i}`);
    const result = decompose(patchset([file(path, filePatch(path, [{ newStart: 1, lines }]))]));

    const fragments = result.hunks.filter((h) => h.splitOf !== undefined);
    expect(fragments.length).toBe(3);
    expect(fragments.map((h) => h.splitOf?.index)).toEqual([0, 1, 2]);
    expect(fragments.every((h) => h.splitOf?.total === 3)).toBe(true);
    // Contiguity + LOC preservation: 400 + 400 + 200 = 1000.
    expect(fragments.map((h) => h.changedLoc)).toEqual([400, 400, 200]);
    expect(fragments.reduce((sum, h) => sum + h.changedLoc, 0)).toBe(1000);

    const substantive = result.chunks.filter((c) => c.kind === "substantive");
    expect(substantive.length).toBe(3);
    for (const chunk of substantive)
      expect(chunk.changedLoc).toBeLessThanOrEqual(DEFAULT_MAX_CHUNK_LOC);
    assertTotality(result);
  });

  it("groups by enclosing symbol when an extractor supplies one", () => {
    const path = "src/grouped.ts";
    const alpha: HunkSpec = { newStart: 1, lines: Array.from({ length: 250 }, (_, i) => `+a${i}`) };
    const beta: HunkSpec = {
      newStart: 300,
      lines: Array.from({ length: 250 }, (_, i) => `+b${i}`),
    };
    const extractor: SymbolExtractor = {
      enclosingSymbols(_path, hunks) {
        return hunks.map((_hunk, index) => (index === 0 ? "alpha" : "beta"));
      },
    };
    // 250 + 250 = 500 > 400, so the two symbol groups land in separate chunks.
    const result = decompose(patchset([file(path, filePatch(path, [alpha, beta]))]), {
      symbolExtractor: extractor,
    });
    const substantive = result.chunks.filter((c) => c.kind === "substantive");
    expect(substantive.map((c) => c.title)).toEqual([
      "src/grouped.ts · alpha",
      "src/grouped.ts · beta",
    ]);
    expect(result.classifications.filter((c) => c.enclosingSymbol === "alpha")).toHaveLength(1);
    expect(result.classifications.filter((c) => c.enclosingSymbol === "beta")).toHaveLength(1);
  });

  it("degrades to file-level grouping with the default extractor ('' symbols)", () => {
    const path = "src/plain.ts";
    const result = decompose(
      patchset([file(path, filePatch(path, [{ lines: ["+const a = 1;"] }]))]),
      { symbolExtractor: DEGRADED_SYMBOL_EXTRACTOR },
    );
    expect(result.classifications.every((c) => c.enclosingSymbol === "")).toBe(true);
    expect(result.chunks[0]?.title).toBe("src/plain.ts");
  });
});

// ── The dependency DAG and reading order ─────────────────────────────────────

describe("dependency DAG and reading order", () => {
  it("derives an enables edge from a relative import and orders the dependency first", () => {
    const model = file(
      "src/model.ts",
      filePatch("src/model.ts", [{ lines: ["+export interface Model {}"] }]),
    );
    const service = file(
      "src/service.ts",
      filePatch("src/service.ts", [
        { lines: ['+import { Model } from "./model";', "+export const s = 1;"] },
      ]),
    );
    const result = decompose(patchset([model, service]));

    const modelChunk = result.chunks.find((c) => c.filePaths[0] === "src/model.ts");
    const serviceChunk = result.chunks.find((c) => c.filePaths[0] === "src/service.ts");
    expect(result.edges).toContainEqual({
      from: modelChunk?.chunkId,
      to: serviceChunk?.chunkId,
      kind: "enables",
    });
    const modelPos = result.readingOrder.indexOf(modelChunk?.chunkId ?? "");
    const servicePos = result.readingOrder.indexOf(serviceChunk?.chunkId ?? "");
    expect(modelPos).toBeLessThan(servicePos);
    assertTopological(result);
  });

  it("breaks an import cycle so the stored edge set is a DAG", () => {
    const a = file(
      "src/a.ts",
      filePatch("src/a.ts", [{ lines: ['+import "./b";', "+export const a = 1;"] }]),
    );
    const b = file(
      "src/b.ts",
      filePatch("src/b.ts", [{ lines: ['+import "./a";', "+export const b = 1;"] }]),
    );
    const result = decompose(patchset([a, b]));

    // Exactly one of the two mutual edges survives; no back-edge closes the cycle.
    expect(result.edges.length).toBe(1);
    const pairs = new Set(result.edges.map((e) => `${e.from}->${e.to}`));
    for (const edge of result.edges) expect(pairs.has(`${edge.to}->${edge.from}`)).toBe(false);
    assertTopological(result);
  });

  it("is byte-stable across two runs on the same patchset", () => {
    const files = [
      file(
        "db/migrations/001_init.sql",
        filePatch("db/migrations/001_init.sql", [{ lines: ["+CREATE TABLE t (id int);"] }]),
      ),
      file("src/model.ts", filePatch("src/model.ts", [{ lines: ["+export interface Model {}"] }])),
      file(
        "src/service.ts",
        filePatch("src/service.ts", [{ lines: ['+import { Model } from "./model";'] }]),
      ),
      file("pnpm-lock.yaml", filePatch("pnpm-lock.yaml", [{ lines: ["+  a: 1"] }])),
    ];
    // The real guarantee: decompose the SAME patchset twice → byte-identical
    // output, no field normalization. (Two separate patchsets with different ids
    // would only test id-normalized equality, which is weaker.)
    const ps = patchset(files);
    const first = decompose(ps);
    const second = decompose(ps);
    expect(JSON.stringify(second)).toBe(JSON.stringify(first));
  });

  it("is independent of the order of patchset.files", () => {
    const files = [
      file(
        "db/migrations/001_init.sql",
        filePatch("db/migrations/001_init.sql", [{ lines: ["+CREATE TABLE t (id int);"] }]),
      ),
      file("src/model.ts", filePatch("src/model.ts", [{ lines: ["+export interface Model {}"] }])),
      file(
        "src/service.ts",
        filePatch("src/service.ts", [{ lines: ['+import { Model } from "./model";'] }]),
      ),
      file("pnpm-lock.yaml", filePatch("pnpm-lock.yaml", [{ lines: ["+  a: 1"] }])),
    ];
    // Same patchset (same id), files array in a DIFFERENT order. The floor's
    // defensive path-sort must make the output identical — proving the ordering
    // is a pure function of file content, not of arrival order.
    const base = patchset(files);
    const reordered = { ...base, files: [...base.files].reverse() };
    const inOrder = decompose(base);
    const shuffled = decompose(reordered);
    expect(JSON.stringify(shuffled)).toBe(JSON.stringify(inOrder));
  });
});

// ── The acceptance case: a real patchset renders offline, no model, no network ─

describe("the floor renders a real patchset with no harness and no network", () => {
  it("produces a complete decomposition from a realistic multi-file patchset", () => {
    const files = [
      file(
        "db/schema.sql",
        filePatch("db/schema.sql", [{ lines: ["+ALTER TABLE users ADD COLUMN age int;"] }]),
      ),
      file(
        "src/model.ts",
        filePatch("src/model.ts", [{ lines: ["+export interface User { age: number; }"] }]),
      ),
      file(
        "src/user-service.ts",
        filePatch("src/user-service.ts", [
          {
            lines: [
              '+import { User } from "./model";',
              "-const a = 1;",
              "+const a = 2;",
              " const keep = true;",
            ],
          },
        ]),
      ),
      file(
        "src/user-service.test.ts",
        filePatch("src/user-service.test.ts", [{ lines: ["+it('works', () => {});"] }]),
      ),
      file("src/style.ts", filePatch("src/style.ts", [{ lines: ["-  a();", "+    a();"] }])),
      file("pnpm-lock.yaml", filePatch("pnpm-lock.yaml", [{ lines: ["+  dep: 2.0.0"] }])),
    ];
    const result = decompose(patchset(files));

    // Every hunk classified; every substantive chunk within budget; totality holds.
    expect(result.classifications.length).toBe(result.hunks.length);
    for (const chunk of result.chunks.filter((c) => c.kind === "substantive")) {
      expect(chunk.changedLoc).toBeLessThanOrEqual(DEFAULT_MAX_CHUNK_LOC);
    }
    assertTotality(result);
    assertTopological(result);

    // The lockfile and the formatting-only change are mechanical (appendix);
    // schema/model/service/test are substantive.
    expect(classOf(result, "pnpm-lock.yaml")).toBe("lockfile");
    expect(classOf(result, "src/style.ts")).toBe("formatting-only");
    const substantiveFiles = new Set(
      result.chunks.filter((c) => c.kind === "substantive").map((c) => c.filePaths[0]),
    );
    expect(substantiveFiles).toContain("db/schema.sql");
    expect(substantiveFiles).toContain("src/model.ts");
    expect(substantiveFiles).toContain("src/user-service.ts");

    // The import edge orders the model before the service that imports it.
    const modelChunk = result.chunks.find((c) => c.filePaths[0] === "src/model.ts");
    const serviceChunk = result.chunks.find((c) => c.filePaths[0] === "src/user-service.ts");
    expect(result.edges).toContainEqual({
      from: modelChunk?.chunkId,
      to: serviceChunk?.chunkId,
      kind: "enables",
    });
  });
});
