/**
 * The shared, deterministic file-classification vocabulary: lockfile, vendored,
 * generated (by path or by header banner) and binary.
 *
 * Two consumers read the same tables, so the changeset view and the repo-wide
 * snapshot view classify the same path the same way:
 *  - `decomposition.ts` stamps a CHANGED file's hunks with a mechanical class, so
 *    a lockfile churn lands in the appendix instead of the review body;
 *  - `knowledge/partition.ts` classifies the WHOLE snapshot inventory, so a
 *    checked-in `dist/` is not batched for mapping (context-map rebuild, W2).
 *
 * They do not see the same evidence, and this module does not pretend they do.
 * Path classification is a pure function of the path and is identical either
 * side. The generated-BANNER check is not: the decomposer sees hunk bodies (so it
 * tracks line numbers through a diff) while the snapshot sees whole blob text, so
 * each owns its own walk over the shared {@link GENERATED_MARKERS} and
 * {@link GENERATED_HEADER_LINES}.
 *
 * Everything here is pure — no clock, no randomness, no IO — because the
 * snapshot-side result is content-addressed.
 */

const LOCKFILE_BASENAMES = new Set([
  "pnpm-lock.yaml",
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "bun.lockb",
  "cargo.lock",
  "poetry.lock",
  "pipfile.lock",
  "gemfile.lock",
  "composer.lock",
  "go.sum",
  "flake.lock",
  "podfile.lock",
  "mix.lock",
  "pubspec.lock",
  "packages.lock.json",
  "gradle.lockfile",
]);

const VENDOR_SEGMENTS = new Set([
  "node_modules",
  "vendor",
  "third_party",
  "third-party",
  "bower_components",
  "pods",
  ".yarn",
  "godeps",
]);

const GENERATED_SEGMENTS = new Set(["dist", "build", "generated", "__generated__"]);

/**
 * Banner phrases a generator emits at the top of a file it owns. Lowercase; the
 * comparison lowercases the candidate line.
 */
export const GENERATED_MARKERS = [
  "@generated",
  "do not edit",
  "code generated by",
  "generated file",
];

/**
 * How many lines of a file count as the "header region" for generated-file marker
 * detection. Generated-file banners ("@generated", "Code generated by …", "DO NOT
 * EDIT") are emitted at the very top of the file by the generator, so a marker
 * beyond this region is not a generated-file signal.
 *
 * Chosen at 10: real banners sit on line 1-2, but a leading license block, a
 * shebang, or a few blank/comment lines can push a banner down a handful of
 * lines, so 10 gives comfortable slack while still excluding the file body.
 */
export const GENERATED_HEADER_LINES = 10;

/**
 * Extensions whose content is not text this codebase can read as source. Used to
 * classify the SNAPSHOT inventory, where there is no diff to carry git's own
 * binary sentinel — the changeset path keeps its structural detection
 * (`Binary files … differ` / `GIT binary patch`) in `decomposition.ts`, which is
 * strictly better evidence when it exists.
 *
 * An extension list is a heuristic and knows it: an extensionless binary, or a
 * novel format, reads as text here. That is the safe direction for this consumer —
 * a mis-kept file is merely batched and read by a worker; a mis-excluded one would
 * vanish from the map.
 */
const BINARY_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".bmp",
  ".ico",
  ".icns",
  ".webp",
  ".avif",
  ".tiff",
  ".psd",
  ".pdf",
  ".zip",
  ".gz",
  ".tgz",
  ".bz2",
  ".xz",
  ".7z",
  ".rar",
  ".jar",
  ".war",
  ".class",
  ".woff",
  ".woff2",
  ".ttf",
  ".otf",
  ".eot",
  ".mp3",
  ".wav",
  ".ogg",
  ".flac",
  ".mp4",
  ".mov",
  ".avi",
  ".webm",
  ".mkv",
  ".so",
  ".dylib",
  ".dll",
  ".exe",
  ".bin",
  ".node",
  ".wasm",
  ".o",
  ".a",
  ".lib",
  ".pyc",
  ".pyo",
  ".db",
  ".sqlite",
  ".sqlite3",
  ".keystore",
  ".jks",
  ".p12",
  ".der",
]);

function basename(path: string): string {
  const parts = path.split("/");
  return parts[parts.length - 1] ?? path;
}

function segments(path: string): string[] {
  return path.split("/").filter(Boolean);
}

function extensionOf(path: string): string {
  const base = basename(path);
  const dot = base.lastIndexOf(".");
  return dot <= 0 ? "" : base.slice(dot).toLowerCase();
}

/** A dependency lockfile: machine-written, enormous, never read line by line. */
export function isLockfile(path: string): boolean {
  return LOCKFILE_BASENAMES.has(basename(path).toLowerCase());
}

/** Third-party code checked into the tree (`node_modules/`, `vendor/`, `pods/`, …). */
export function isVendored(path: string): boolean {
  return segments(path).some((s) => VENDOR_SEGMENTS.has(s.toLowerCase()));
}

/** Generated by PATH signal alone: a build output directory, or a generator's naming convention. */
export function isGeneratedPath(path: string): boolean {
  const base = basename(path).toLowerCase();
  if (/\.(min\.js|min\.css|map)$/.test(base)) return true;
  if (/\.pb\.go$/.test(base) || /_pb2\.py$/.test(base) || /\.g\.dart$/.test(base)) return true;
  if (/\.generated\./.test(base)) return true;
  return segments(path).some((s) => GENERATED_SEGMENTS.has(s.toLowerCase()));
}

/** Binary by extension — the inventory-side counterpart of the diff's binary sentinels. */
export function isBinaryPath(path: string): boolean {
  return BINARY_EXTENSIONS.has(extensionOf(path));
}

/**
 * Whether a file's TEXT opens with a generator's banner. A pure function of the
 * bytes (so a snapshot shard carrying the answer stays content-addressed): the
 * first {@link GENERATED_HEADER_LINES} physical lines are lowercased and matched
 * against {@link GENERATED_MARKERS}.
 *
 * Deliberately bounded to the header: a file that merely MENTIONS "do not edit"
 * in its body is hand-written prose, and treating it as generated would delete a
 * real file from the map.
 */
export function hasGeneratedMarker(text: string): boolean {
  const lines = text.split("\n", GENERATED_HEADER_LINES);
  for (const line of lines) {
    const lower = line.toLowerCase();
    if (GENERATED_MARKERS.some((marker) => lower.includes(marker))) return true;
  }
  return false;
}

/**
 * Why a file is not worth spending a mapping worker's turn on. Ordered by how
 * decisive the evidence is, and reported rather than silently dropped — the
 * inventory keeps the file, so the map stays honest about what exists.
 */
export type MappingIneligibility =
  | "binary"
  | "lockfile"
  | "vendored"
  | "generated-path"
  | "generated-content";

/**
 * Classify one inventory file's mapping eligibility: the ineligibility reason, or
 * `null` when the file is worth mapping. Deterministic and total.
 *
 * `generatedContent` is the blob-text answer from {@link hasGeneratedMarker},
 * supplied by whatever already read the bytes (the snapshot generator reads each
 * blob once). Pass `false`/omit when the text was never read — the path signals
 * still apply, and a missed banner keeps a file in the map rather than dropping
 * one that belongs there.
 *
 * Check order is fixed so the reported reason is stable: the strongest structural
 * signal first (binary content cannot be read at all), then the three path
 * signals, then the content banner — so `dist/bundle.min.js` reports
 * `generated-path` rather than whichever check happened to run first.
 */
export function classifyMappingEligibility(
  path: string,
  generatedContent = false,
): MappingIneligibility | null {
  if (isBinaryPath(path)) return "binary";
  if (isLockfile(path)) return "lockfile";
  if (isVendored(path)) return "vendored";
  if (isGeneratedPath(path)) return "generated-path";
  if (generatedContent) return "generated-content";
  return null;
}

/** One inventory file's mapping verdict. */
export interface InventoryClassification {
  readonly path: string;
  readonly blobOid: string;
  /** The exclusion reason, or `null` when the file is worth mapping. */
  readonly ineligible: MappingIneligibility | null;
}

/**
 * Classify a whole snapshot inventory, in path order.
 *
 * ⭐ EVERY input file appears in the output. Exclusion is RECORDED, never a
 * deletion: the map stays truthful about what the tree contains, and a reader who
 * asks "why is `dist/bundle.js` not described?" gets `generated-path` rather than
 * silence. Only the batcher acts on the verdict.
 *
 * `generatedBlobs` names the blobs whose text carried a generator banner (the
 * snapshot's symbol shards answer this). An empty set is a legitimate input — it
 * simply means no content evidence was available, and the path signals stand alone.
 */
export function classifyInventory(
  files: readonly { readonly path: string; readonly blobOid: string }[],
  generatedBlobs: ReadonlySet<string> = new Set(),
): readonly InventoryClassification[] {
  return [...files]
    .sort((l, r) => (l.path < r.path ? -1 : l.path > r.path ? 1 : 0))
    .map((file) => ({
      path: file.path,
      blobOid: file.blobOid,
      ineligible: classifyMappingEligibility(file.path, generatedBlobs.has(file.blobOid)),
    }));
}
