import { describe, expect, it } from "vitest";
import {
  classifyInventory,
  classifyMappingEligibility,
  GENERATED_HEADER_LINES,
  hasGeneratedMarker,
  isBinaryPath,
  isGeneratedPath,
  isLockfile,
  isVendored,
} from "./file-classification";

// The vocabulary the changeset decomposer and the repo-wide snapshot classifier
// share. Tested here rather than through either consumer: a drifted table would
// otherwise show up as two unrelated bugs.

describe("path classifiers", () => {
  it("names lockfiles by basename, case-insensitively, at any depth", () => {
    expect(isLockfile("pnpm-lock.yaml")).toBe(true);
    expect(isLockfile("apps/desktop/Cargo.lock")).toBe(true);
    expect(isLockfile("packages/core/src/lockfile.ts")).toBe(false);
  });

  it("names vendored trees by path segment, never by substring", () => {
    expect(isVendored("node_modules/left-pad/index.js")).toBe(true);
    expect(isVendored("ios/Pods/Foo.m")).toBe(true);
    // A segment match, not a substring one: `vendored-ui` is our own code.
    expect(isVendored("packages/vendored-ui/src/a.ts")).toBe(false);
  });

  it("names generated paths by build directory and by generator naming convention", () => {
    expect(isGeneratedPath("packages/core/dist/index.js")).toBe(true);
    expect(isGeneratedPath("web/static/app.min.js")).toBe(true);
    expect(isGeneratedPath("api/service.pb.go")).toBe(true);
    expect(isGeneratedPath("src/schema.generated.ts")).toBe(true);
    expect(isGeneratedPath("packages/core/src/build-plan.ts")).toBe(false);
  });

  it("names binaries by extension, and leaves an unknown extension as text", () => {
    expect(isBinaryPath("assets/logo.png")).toBe(true);
    expect(isBinaryPath("native/addon.node")).toBe(true);
    expect(isBinaryPath("docs/guide.md")).toBe(false);
    // The stated ceiling: an extensionless binary reads as text here.
    expect(isBinaryPath("bin/some-compiled-thing")).toBe(false);
  });
});

describe("hasGeneratedMarker — the one content-derived signal", () => {
  it("finds each banner phrase, case-insensitively, in the header region", () => {
    expect(hasGeneratedMarker("// @generated by codegen\nexport const a = 1;\n")).toBe(true);
    expect(hasGeneratedMarker("// Code generated by protoc. DO NOT EDIT.\n")).toBe(true);
    expect(hasGeneratedMarker("/* GENERATED FILE */\n")).toBe(true);
    expect(hasGeneratedMarker("#!/usr/bin/env node\n\n// do not edit\n")).toBe(true);
  });

  it("ignores a banner phrase below the header region", () => {
    // A hand-written file that merely MENTIONS the phrase deep in its body is not
    // generated, and treating it as such would delete a real file from the map.
    const deep = `${"\n".repeat(GENERATED_HEADER_LINES + 2)}// do not edit this by hand\n`;
    expect(hasGeneratedMarker(deep)).toBe(false);
    // The positive control: the same phrase on line 1 IS a banner.
    expect(hasGeneratedMarker("// do not edit this by hand\n")).toBe(true);
  });

  it("is false for ordinary source", () => {
    expect(hasGeneratedMarker("export function a(): void {}\n")).toBe(false);
  });
});

describe("classifyMappingEligibility — a stable reason per file", () => {
  it("reports each reason", () => {
    expect(classifyMappingEligibility("assets/logo.png")).toBe("binary");
    expect(classifyMappingEligibility("pnpm-lock.yaml")).toBe("lockfile");
    expect(classifyMappingEligibility("node_modules/x/i.js")).toBe("vendored");
    expect(classifyMappingEligibility("packages/core/dist/i.js")).toBe("generated-path");
    expect(classifyMappingEligibility("packages/core/src/api.ts", true)).toBe("generated-content");
  });

  it("passes ordinary source", () => {
    expect(classifyMappingEligibility("packages/core/src/api.ts")).toBeNull();
    expect(classifyMappingEligibility("docs/guide.md")).toBeNull();
  });

  it("prefers the path signal over the content one, so the reason is stable", () => {
    // `dist/bundle.js` with a banner is reported as `generated-path`, not
    // `generated-content`: the reason a reader is shown must not depend on which
    // check happened to run first.
    expect(classifyMappingEligibility("packages/core/dist/bundle.js", true)).toBe("generated-path");
  });
});

describe("classifyInventory — exclusion is RECORDED, never a deletion", () => {
  const inventory = [
    { path: "packages/core/src/b.ts", blobOid: "blob-b" },
    { path: "packages/core/dist/b.js", blobOid: "blob-dist" },
    { path: "packages/core/src/a.ts", blobOid: "blob-a" },
    { path: "pnpm-lock.yaml", blobOid: "blob-lock" },
  ];

  it("returns EVERY input file, in path order, with its verdict", () => {
    const out = classifyInventory(inventory);
    expect(out.map((c) => c.path)).toEqual([
      "packages/core/dist/b.js",
      "packages/core/src/a.ts",
      "packages/core/src/b.ts",
      "pnpm-lock.yaml",
    ]);
    expect(out.map((c) => c.ineligible)).toEqual(["generated-path", null, null, "lockfile"]);
    expect(out.every((c) => c.blobOid !== "")).toBe(true);
  });

  it("applies the content signal by BLOB, so a copied generated file is caught at both paths", () => {
    const copied = [
      { path: "src/client.ts", blobOid: "blob-gen" },
      { path: "src/client-copy.ts", blobOid: "blob-gen" },
      { path: "src/hand-written.ts", blobOid: "blob-hand" },
    ];
    const out = classifyInventory(copied, new Set(["blob-gen"]));
    expect(out.map((c) => c.ineligible)).toEqual(["generated-content", "generated-content", null]);
    // The control: with no content evidence the same tree is fully eligible.
    expect(classifyInventory(copied).every((c) => c.ineligible === null)).toBe(true);
  });
});
