import type { OpenSpecChange } from "@rennet/types";

// A real `OpenSpecChange`, generated by parsing the real
// `openspec/changes/deliver-real-diff-on-zoom/` artifact set through
// `@rennet/core parseOpenSpecChange` and freezing the result (openspec/ is
// gitignored and `@rennet/ui` cannot import `@rennet/core`, so the parse output is
// captured here as a static literal — the demo the spec angle renders until a live
// change is wired in). Regenerate by re-parsing that change and replacing the literal.
export const OPENSPEC_FIXTURE: OpenSpecChange = {
  name: "deliver-real-diff-on-zoom",
  meta: {
    schema: "spec-driven",
    created: "2026-08-07",
  },
  proposal: {
    why: {
      heading: "Why",
      level: 2,
      body: "After #54 the canvas STATE is real (derived from the real decomposition of the real diff), but zooming into a canvas element to see the code still renders `demoDiff(400)` — a synthetic fixture. `packages/ui/src/app.tsx` wires `diffFor={(k) => ({ path: k, diff: demoDiff(400) })}`, so the last mile of Rai's #1 product ask — \"I want to see the actual code\" — is unmet: the reviewer navigates real canvases but the diff surface is a fake.\n\nThe real hunk material already exists on the live path: `decompose` (#7) derives every chunk's hunks from the real `git diff`, and `buildReviewCanvases` (#54) already has the decomposition and the patchset in scope. Nothing delivers that hunk content to the UI's zoom surface.",
      anchor: {
        id: "proposal:why",
        artifact: "proposal",
        path: "why",
        label: "Why",
      },
    },
    whatChanges: {
      heading: "What Changes",
      level: 2,
      body: "- Add `buildElementDiffs` to `@rennet/core` (new `element-diffs.ts`): a **pure** function of `(canvases, decomposition, patchset)` that resolves each canvas element's `rennet:chunk/<id>` / `rennet:hunk/<id>` anchor to the **verbatim** raw-hunk text sliced from the real `patchset.files[].patch`. Doc-anchored elements (flat angles) resolve to nothing (no code diff). The output is `ElementDiffs = Record<elementKey, { path, diff }>`.\n- Deliver `elementDiffs` with the canvas response: `buildReviewCanvases` returns it in its result; the `review.canvases` protocol output gains a required `elementDiffs` map; desktop dispatch passes it through.\n- Wire the UI: `loadCanvases` returns `{ canvases, elementDiffs }`; `RennetApp` stores both and a `liveLoaded` flag, and `diffFor` reads the **real** map on the real path — falling back to `demoDiff(400)` **only** while the fixtures demo is on screen, so the demo never regresses.\n- The diff text is byte-faithful to git (sliced verbatim from the captured patch, never reconstructed from separated add/del/context arrays), so the zoom shows exactly what was captured.",
      anchor: {
        id: "proposal:whatChanges",
        artifact: "proposal",
        path: "whatChanges",
        label: "What Changes",
      },
    },
    capabilities: [
      {
        kind: "modified",
        name: "live-review-pipeline",
        description:
          "the five-angle canvas set delivered over `review.canvases` now carries a per-element real diff map, so zooming into a canvas element renders the real captured hunk content instead of the `demoDiff` fixture.",
        anchor: {
          id: "proposal:capabilities/0",
          artifact: "proposal",
          path: "capabilities/0",
          label: "live-review-pipeline",
        },
      },
    ],
    impact: {
      heading: "Impact",
      level: 2,
      body: "- Adds `packages/core/src/element-diffs.ts`; adds `ElementDiff`/`ElementDiffs` to `@rennet/types`; extends `buildReviewCanvases` in `packages/core/src/pipeline.ts`.\n- Extends the `review.canvases` output schema in `packages/protocol/src/index.ts` (required `elementDiffs`).\n- `apps/desktop/src/main/dispatch.ts` + `index.ts`: `buildCanvases` returns `{ canvases, elementDiffs }`; the handler returns both.\n- `packages/ui/src/canvas/load.ts` + `app.tsx`: real diff on the real path, `demoDiff` preserved on the demo path.\n- No new package, no new runtime dependency, no dependency-arrow change. `element-diffs.ts` is a pure string transform over `@rennet/types` + `parseAnchor` (already a `core → protocol` edge). `layer:ui` stays clean (the UI reads diffs over the bridge, never runs the slicer).",
      anchor: {
        id: "proposal:impact",
        artifact: "proposal",
        path: "impact",
        label: "Impact",
      },
    },
    anchor: {
      id: "proposal:",
      artifact: "proposal",
      path: "",
      label: "Proposal",
    },
  },
  design: {
    sections: [
      {
        heading: "Delivery path: canvas-response, not lazy `diff.read`",
        level: 2,
        body: "The `review.canvases` command is an on-demand fetch (opened Canvases view), not a stream. Delivering the per-element diffs **alongside** the canvas set is the cleaner path:\n\n- One round-trip. `diffFor` stays synchronous (`(elementKey) => { path, diff } | undefined`) — no async plumbing into `CodeView`, no new IPC command, no per-element fetch storm on zoom.\n- The payload is bounded by the captured patchset, which is already byte-bounded and truncatable (`Patchset.byteLength` / `truncated`). The diff map is a re-slice of bytes the response already implies; it is not heavier than the patch itself.\n\nA lazy `diff.read` would add an IPC command, an async loading state in the zoom surface, and a round-trip per element — real cost for no benefit at this payload size. Reach for it only if a future changeset makes the eager map too heavy; the shape here (`Record<elementKey, {path, diff}>`) is the same data either way.",
        anchor: {
          id: "design:0",
          artifact: "design",
          path: "0",
          label: "Delivery path: canvas-response, not lazy `diff.read`",
        },
      },
      {
        heading: "Where the real hunk material lives, and how it is sliced",
        level: 2,
        body: "`decompose` (#7) parses each `patchset.files[].patch` into `Hunk`s, but stores the body as **separated** `addedLines` / `deletedLines` / `contextLines` arrays — the interleaved order is lost there. Reconstructing a diff from those arrays would **reorder** the lines (all deletions, then all additions), producing a plausible-but-wrong render. That is the exact failure to avoid: a viewer that silently transforms what it shows.\n\nSo the slicer goes back to the **verbatim** source: it re-parses `patchset.files[].patch` into raw `@@` hunks, keeping each hunk's header line and body lines exactly as captured, and maps each decomposition `Hunk` to the raw hunk whose new/old line range **contains** it. Non-split hunks match their raw hunk exactly; oversize split fragments (`splitOf`) fall within their parent raw hunk and collapse back to it (shown once, in full — real, never fabricated). Distinct raw hunks per element are rendered in file order.\n\nAnchor resolution (`parseAnchor` from `@rennet/protocol`):\n- `rennet:chunk/<chunkId>` → the chunk's `hunkIds` → their decomposition hunks → distinct raw hunks. Path = the chunk's file.\n- `rennet:hunk/<hunkId>` → that one hunk → its raw hunk. Path = the hunk's file.\n- anything else (`doc`, `spec`, …) → no entry. The flat-angle elements have no code diff; `diffFor` returns `undefined` and the zoom surface is simply not shown (honest, not fabricated).\n- synthetic-only hunks (pure rename / mode-only / binary — no `@@` body) → fall back to the file's verbatim `patch` if it carries content, else no entry.\n\nThe slicer is a pure function of `(canvases, decomposition, patchset)`: no clock, no fs, no model. Same inputs → byte-identical `elementDiffs`.",
        anchor: {
          id: "design:1",
          artifact: "design",
          path: "1",
          label: "Where the real hunk material lives, and how it is sliced",
        },
      },
      {
        heading: "Why not touch the `Canvas` type",
        level: 2,
        body: "The `Canvas` / `AnalysisElement` shapes are frozen from #10 and carry a byte-identical-replay invariant (`canvasDigest`). Embedding diff text on each element would mutate that shape and bloat the canvas digest. The diff map is a **sibling** of the canvas set, keyed by the same `elementKey`, so the canvas projection stays byte-identical and the diff delivery is purely additive.",
        anchor: {
          id: "design:2",
          artifact: "design",
          path: "2",
          label: "Why not touch the `Canvas` type",
        },
      },
      {
        heading: "Preserving the fixtures demo",
        level: 2,
        body: "`RennetApp` seeds `canvases` from `demoCanvases()` and replaces them on the first successful `loadCanvases`. A `liveLoaded` boolean records whether the on-screen canvases are the real set. `diffFor` branches on it: real map when `liveLoaded`, `demoDiff(400)` while the demo is up. The demo path is byte-unchanged; only the real path shows real code. A missing key on the real path (a doc-anchored element) yields `undefined`, and the zoom surface is correctly hidden rather than showing a fixture.",
        anchor: {
          id: "design:3",
          artifact: "design",
          path: "3",
          label: "Preserving the fixtures demo",
        },
      },
      {
        heading: "Testing (no DOM env in `packages/ui`, per #53)",
        level: 2,
        body: "The strongest surface is core, and the acceptance criterion is a data-path assertion:\n- `buildElementDiffs` / `buildReviewCanvases` over a real captured patchset → the sequence canvas's chunk element carries a diff whose lines trace to the **real** patch (exact added/context lines present) and whose text contains **no** `demoDiff` signature.\n- Red-capable: without the delivery, `elementDiffs` is empty and the element lookup is `undefined` — the test fails.\n- Protocol: the `review.canvases` output round-trips `elementDiffs`, and a malformed entry is rejected (positive control).\n- UI: `load.test.ts` asserts `loadCanvases` returns the diffs; the `diffFor` wiring is read-verified + typecheck-covered (no DOM test env).",
        anchor: {
          id: "design:4",
          artifact: "design",
          path: "4",
          label: "Testing (no DOM env in `packages/ui`, per #53)",
        },
      },
    ],
    anchor: {
      id: "design:",
      artifact: "design",
      path: "",
      label: "Design",
    },
  },
  tasks: {
    groups: [
      {
        ordinal: "1",
        title: "Types: the shared diff shape",
        items: [
          {
            ordinal: "1.1",
            text: "Add `ElementDiff { path: string; diff: string }` and `ElementDiffs = Record<string, ElementDiff>` to `@rennet/types`",
            checked: false,
            anchor: {
              id: "tasks:groups/0/items/0",
              artifact: "tasks",
              path: "groups/0/items/0",
              label: "1.1",
            },
          },
        ],
        anchor: {
          id: "tasks:groups/0",
          artifact: "tasks",
          path: "groups/0",
          label: "1. Types: the shared diff shape",
        },
      },
      {
        ordinal: "2",
        title: "Core: the diff slicer (TDD)",
        items: [
          {
            ordinal: "2.1",
            text: "Test (red first): `buildElementDiffs(canvases, decomposition, patchset)` over a real patchset → the sequence chunk element's diff carries the real added/context lines (verbatim), path = the file; a doc-anchored element has no entry; `demoDiff` signature absent",
            checked: false,
            anchor: {
              id: "tasks:groups/1/items/0",
              artifact: "tasks",
              path: "groups/1/items/0",
              label: "2.1",
            },
          },
          {
            ordinal: "2.2",
            text: "`element-diffs.ts`: parse `patchset.files[].patch` into verbatim raw `@@` hunks; map each decomposition `Hunk` to its containing raw hunk; resolve `chunk`/`hunk` anchors to distinct raw-hunk text (file order); doc anchors → no entry; synthetic-only → file `patch` fallback",
            checked: false,
            anchor: {
              id: "tasks:groups/1/items/1",
              artifact: "tasks",
              path: "groups/1/items/1",
              label: "2.2",
            },
          },
          {
            ordinal: "2.3",
            text: "Test: hunk-anchor element resolves to that single hunk; split-fragment chunk collapses to its parent raw hunk once (no duplication); pure function (same inputs → identical output)",
            checked: false,
            anchor: {
              id: "tasks:groups/1/items/2",
              artifact: "tasks",
              path: "groups/1/items/2",
              label: "2.3",
            },
          },
        ],
        anchor: {
          id: "tasks:groups/1",
          artifact: "tasks",
          path: "groups/1",
          label: "2. Core: the diff slicer (TDD)",
        },
      },
      {
        ordinal: "3",
        title: "Core: deliver with the pipeline result",
        items: [
          {
            ordinal: "3.1",
            text: "`buildReviewCanvases` returns `elementDiffs` in `ReviewPipelineResult` (computed from the built canvases + decomposition + patchset)",
            checked: false,
            anchor: {
              id: "tasks:groups/2/items/0",
              artifact: "tasks",
              path: "groups/2/items/0",
              label: "3.1",
            },
          },
          {
            ordinal: "3.2",
            text: "Test: `buildReviewCanvases` result carries `elementDiffs` for the sequence chunk elements on the floor path (no model)",
            checked: false,
            anchor: {
              id: "tasks:groups/2/items/1",
              artifact: "tasks",
              path: "groups/2/items/1",
              label: "3.2",
            },
          },
        ],
        anchor: {
          id: "tasks:groups/2",
          artifact: "tasks",
          path: "groups/2",
          label: "3. Core: deliver with the pipeline result",
        },
      },
      {
        ordinal: "4",
        title: "Protocol: extend the `review.canvases` output",
        items: [
          {
            ordinal: "4.1",
            text: "Add a required `elementDiffs` map (`Record<string, {path, diff}>`) to the `review.canvases` output schema",
            checked: false,
            anchor: {
              id: "tasks:groups/3/items/0",
              artifact: "tasks",
              path: "groups/3/items/0",
              label: "4.1",
            },
          },
          {
            ordinal: "4.2",
            text: "Update the existing round-trip test to include `elementDiffs`; add a round-trip assertion + a malformed-entry positive control",
            checked: false,
            anchor: {
              id: "tasks:groups/3/items/1",
              artifact: "tasks",
              path: "groups/3/items/1",
              label: "4.2",
            },
          },
        ],
        anchor: {
          id: "tasks:groups/3",
          artifact: "tasks",
          path: "groups/3",
          label: "4. Protocol: extend the `review.canvases` output",
        },
      },
      {
        ordinal: "5",
        title: "Desktop: pass it through",
        items: [
          {
            ordinal: "5.1",
            text: "`DispatchDeps.buildCanvases` returns `{ canvases, elementDiffs }`; the `review.canvases` handler returns both",
            checked: false,
            anchor: {
              id: "tasks:groups/4/items/0",
              artifact: "tasks",
              path: "groups/4/items/0",
              label: "5.1",
            },
          },
          {
            ordinal: "5.2",
            text: "`buildCanvasesForReview` returns `{ canvases, elementDiffs }` from the pipeline result",
            checked: false,
            anchor: {
              id: "tasks:groups/4/items/1",
              artifact: "tasks",
              path: "groups/4/items/1",
              label: "5.2",
            },
          },
        ],
        anchor: {
          id: "tasks:groups/4",
          artifact: "tasks",
          path: "groups/4",
          label: "5. Desktop: pass it through",
        },
      },
      {
        ordinal: "6",
        title: "UI: real diff on the real path, demo preserved",
        items: [
          {
            ordinal: "6.1",
            text: "`loadCanvases` returns `{ canvases, elementDiffs } | null`; update `load.test.ts`",
            checked: false,
            anchor: {
              id: "tasks:groups/5/items/0",
              artifact: "tasks",
              path: "groups/5/items/0",
              label: "6.1",
            },
          },
          {
            ordinal: "6.2",
            text: "`RennetApp` stores `elementDiffs` + a `liveLoaded` flag; `diffFor` reads the real map when live, `demoDiff(400)` while the demo is up",
            checked: false,
            anchor: {
              id: "tasks:groups/5/items/1",
              artifact: "tasks",
              path: "groups/5/items/1",
              label: "6.2",
            },
          },
          {
            ordinal: "6.3",
            text: "Read-verify the wiring; `demoCanvases()` / `demoDiff` fallback byte-unchanged",
            checked: false,
            anchor: {
              id: "tasks:groups/5/items/2",
              artifact: "tasks",
              path: "groups/5/items/2",
              label: "6.3",
            },
          },
        ],
        anchor: {
          id: "tasks:groups/5",
          artifact: "tasks",
          path: "groups/5",
          label: "6. UI: real diff on the real path, demo preserved",
        },
      },
      {
        ordinal: "7",
        title: "Gate",
        items: [
          {
            ordinal: "7.1",
            text: "`pnpm check` green (real checker, not tsgo); push; verify `origin==HEAD`; open PR (do not merge)",
            checked: false,
            anchor: {
              id: "tasks:groups/6/items/0",
              artifact: "tasks",
              path: "groups/6/items/0",
              label: "7.1",
            },
          },
        ],
        anchor: {
          id: "tasks:groups/6",
          artifact: "tasks",
          path: "groups/6",
          label: "7. Gate",
        },
      },
    ],
    total: 14,
    completed: 0,
    anchor: {
      id: "tasks:",
      artifact: "tasks",
      path: "",
      label: "Tasks",
    },
  },
  specDeltas: [
    {
      capability: "live-review-pipeline",
      intro:
        "Delivery of the real per-element diff material with the live canvas set, so zooming into a canvas element renders the real captured hunk content.",
      operations: [
        {
          operation: "added",
          requirements: [
            {
              name: "The canvas response carries a real per-element diff map",
              text: "`buildReviewCanvases` SHALL produce, alongside the five-angle canvas set, an `elementDiffs` map keyed by `elementKey`. Each entry SHALL carry the changed file `path` and the `diff` text sliced **verbatim** from the captured `Patchset` — never reconstructed from separated add/delete/context arrays, and never a fixture. The `review.canvases` command output SHALL deliver this map to the renderer.\n\nThe map SHALL be a pure function of `(canvases, decomposition, patchset)`: identical inputs SHALL yield an identical map.",
              scenarios: [
                {
                  name: "a chunk element resolves to its real captured hunk",
                  steps: [
                    {
                      keyword: "WHEN",
                      text: "`buildReviewCanvases` runs on a real patchset (deterministic floor, no model turn)",
                    },
                    {
                      keyword: "THEN",
                      text: "the sequence canvas's chunk element has an `elementDiffs` entry whose `path` is the changed file",
                    },
                    {
                      keyword: "AND",
                      text: "the entry's `diff` contains the real added and context lines exactly as captured in the patch",
                    },
                    {
                      keyword: "AND",
                      text: "the `diff` contains no `demoDiff` fixture signature",
                    },
                  ],
                  anchor: {
                    id: "spec:live-review-pipeline/operations/0/requirements/0/scenarios/0",
                    artifact: "spec",
                    path: "live-review-pipeline/operations/0/requirements/0/scenarios/0",
                    label: "a chunk element resolves to its real captured hunk",
                  },
                },
                {
                  name: "a doc-anchored element has no diff",
                  steps: [
                    {
                      keyword: "WHEN",
                      text: "an element's anchor is not a `chunk` or `hunk` anchor (a flat-angle document element)",
                    },
                    {
                      keyword: "THEN",
                      text: "it has no `elementDiffs` entry, so the zoom surface renders nothing rather than a fixture",
                    },
                  ],
                  anchor: {
                    id: "spec:live-review-pipeline/operations/0/requirements/0/scenarios/1",
                    artifact: "spec",
                    path: "live-review-pipeline/operations/0/requirements/0/scenarios/1",
                    label: "a doc-anchored element has no diff",
                  },
                },
              ],
              anchor: {
                id: "spec:live-review-pipeline/operations/0/requirements/0",
                artifact: "spec",
                path: "live-review-pipeline/operations/0/requirements/0",
                label: "The canvas response carries a real per-element diff map",
              },
            },
            {
              name: "The zoom surface renders the real diff on the real path",
              text: "The canvas UI SHALL render the `elementDiffs` diff for the selected element when a real review is loaded, replacing the `demoDiff` fixture. The fixtures demo path SHALL be unchanged: when no real canvas set has loaded, zooming SHALL still render the demo diff, so the clickable demo never regresses.",
              scenarios: [
                {
                  name: "real review shows real code",
                  steps: [
                    {
                      keyword: "WHEN",
                      text: "a real canvas set has loaded and the user zooms into an element that has an `elementDiffs` entry",
                    },
                    {
                      keyword: "THEN",
                      text: "the diff surface renders that real diff, not `demoDiff`",
                    },
                  ],
                  anchor: {
                    id: "spec:live-review-pipeline/operations/0/requirements/1/scenarios/0",
                    artifact: "spec",
                    path: "live-review-pipeline/operations/0/requirements/1/scenarios/0",
                    label: "real review shows real code",
                  },
                },
                {
                  name: "the fixtures demo is preserved",
                  steps: [
                    {
                      keyword: "WHEN",
                      text: "no real canvas set has loaded (the fixtures demo is on screen)",
                    },
                    {
                      keyword: "THEN",
                      text: "zooming still renders the demo diff, unchanged",
                    },
                  ],
                  anchor: {
                    id: "spec:live-review-pipeline/operations/0/requirements/1/scenarios/1",
                    artifact: "spec",
                    path: "live-review-pipeline/operations/0/requirements/1/scenarios/1",
                    label: "the fixtures demo is preserved",
                  },
                },
              ],
              anchor: {
                id: "spec:live-review-pipeline/operations/0/requirements/1",
                artifact: "spec",
                path: "live-review-pipeline/operations/0/requirements/1",
                label: "The zoom surface renders the real diff on the real path",
              },
            },
          ],
          anchor: {
            id: "spec:live-review-pipeline/operations/0",
            artifact: "spec",
            path: "live-review-pipeline/operations/0",
            label: "added",
          },
        },
      ],
      requirementCount: 2,
      anchor: {
        id: "spec:live-review-pipeline",
        artifact: "spec",
        path: "live-review-pipeline",
        label: "live-review-pipeline",
      },
    },
  ],
};

/** The demo OpenSpec change the spec angle renders when no live change is provided. */
export function demoOpenSpecChange(): OpenSpecChange {
  return OPENSPEC_FIXTURE;
}
